server:
  port: ${windrop.port:8898}
  compression:
    #开启gzip压缩将enabled值改为on
    enabled: off
    mime-types: application/*,text/plain,image/*
    min-response-size: 20MB

spring:
  servlet:
    multipart:
      max-request-size: 29MB
  codec:
    max-in-memory-size: 50MB
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    valid: debug
  file:
    name: logs/server.log
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 20MB
      clean-history-on-start: true
