server:
  port: ${windrop.port:8898}

spring:
  servlet:
    multipart:
      max-request-size: 29MB
  codec:
    max-in-memory-size: 50MB
  security:
    user:
      name: ${windrop.username:}
      #      password: $2a$10$ZcpJcjag3FtdJhwPmFBo4OMtiHSjblmUQ4rCKCaJzKPFAWjFJGKja
      password: ${windrop.password:}
  thymeleaf:
    cache: false

logging:
  level:
    root: info
  file:
    max-history: 1
    max-size: 20MB
    clean-history-on-start: true
    name: logs/server.log
